### ISSUE TITLE
No report on permissions

### ISSUE THREAD

**Issue by samcbryant** [daltschu22/crawlinator#2]
running the script against a directory in which I have mixed permissions to (some files and directories I can read some I can't), there is no message that I don't have permission to read directories or files

This causes the data reported back to be true only on items I can read, and not the entire directory I have asked it to review

need to include code that can report this back to the user executing the script

**Comment by daltschu22** [comment]
Fixed in [0451ea1](https://github.com/daltschu22/crawlinator/commit/0451ea157fb64ccd88e8bdbaab9ce65c57de8ac0)

Now displays failures, for example:
'Failures': [   '/var/cache/ldconfig',
                    '/var/lib/polkit-1',
                    '/var/lib/sudo',
                    '/var/spool/cron/atjobs',
                    '/var/spool/cron/atspool',
                    '/var/spool/cron/crontabs',
                    '/var/spool/rsyslog']
